In [12]:
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

TIMESTEPS = 86400 # Number of seconds in a day of operation

In [13]:
index_name_list = ['genset_capacity','li_capacity','flow_capacity','flywheel_capacity','load_min', 'pv_capacity']

In [14]:
def random_values_for_params(df_constants=[{}]) -> pd.DataFrame:
    for i in index_name_list:
        df_constants[i] = np.random.randint(0,1.5E3)
    df_constants['component_cost_max'] = np.random.randint(5E5,1.5E6)
    return df_constants

In [15]:
def create_test_grid(max_cost = 0):
    df_grid = pd.DataFrame() # Create Formated Dataframe
    df_grid['ramping_rate'] = [12] # Power per second in kW/s
    df_grid['capacity_cost'] = [335] # Cost of installation for average internal combustion generator sets in USD $ 
    # Storage of Test Grid
    #df_grid['li_capacity'] = 1 # Capacity In kWh
    df_grid['li_max_discharge'] = [1] # Max power output kilowatts
    df_grid['li_max_charge'] = [1] # Max power input kilowatts
    df_grid['li_cost_per_kWh'] = [135] # in USD $
    #  Ion Flow 
    df_grid['flow_max_discharge'] = [20] # Max power output in kilowatts
    df_grid['flow_max_charge'] = [20] # Max power input in kilowatts
    df_grid['flow_cost_per_kWh'] = [54] # in USD $
    # FlywheeL Storage
    df_grid['flywheeel_max_discharge'] = [8] #Max power output in kilowatts
    df_grid['flywheeel_max_charge'] = [8] #Max power input in kilowatts
    df_grid['flywheel_cost_per_kWh'] = [330] # in USD $
    #Grid Restrictions
    # Highest ammount that the all grid components can cost (installation not included) in $ (component cost is varible)
    df_grid['component_cost_max'] = [max_cost]
    # Local Power cost in $
    df_grid['local_power_cost'] = [0.11] # $USD per kWh
    # Uptime of the microgrid if main grid goes down
    return df_grid

In [16]:
df_microgrid = create_test_grid(max_cost= 1E6)
display(df_microgrid)

,ramping_rate,capacity_cost,li_max_discharge,li_max_charge,li_cost_per_kWh,flow_max_discharge,flow_max_charge,flow_cost_per_kWh,flywheeel_max_discharge,flywheeel_max_charge,flywheel_cost_per_kWh,component_cost_max,local_power_cost
0,12,335,1,1,135,20,20,54,8,8,330,1000000.0,0.11

In [17]:
display(random_values_for_params(df_constants=df_microgrid))

,ramping_rate,capacity_cost,li_max_discharge,li_max_charge,li_cost_per_kWh,flow_max_discharge,flow_max_charge,flow_cost_per_kWh,flywheeel_max_discharge,flywheeel_max_charge,flywheel_cost_per_kWh,component_cost_max,local_power_cost,genset_capacity,li_capacity,flow_capacity,flywheel_capacity,load_min,pv_capacity
0,12,335,1,1,135,20,20,54,8,8,330,1458592,0.11,1139,784,518,1388,43,1018

In [18]:
def make_random_grids(n=1, max_cost=0, df_constants=df_microgrid):
    df_training_microgrids = pd.DataFrame()
    i = 0
    while i < n:
        df_rand = random_values_for_params(df_constants=df_microgrid)
        df_training_microgrids = df_training_microgrids.append(df_rand, ignore_index= True)
        i=i+1
    return df_training_microgrids

In [19]:
df_microgrid_list = make_random_grids(5,max_cost=1E6,df_constants=df_microgrid)
display(df_microgrid_list)

,ramping_rate,capacity_cost,li_max_discharge,li_max_charge,li_cost_per_kWh,flow_max_discharge,flow_max_charge,flow_cost_per_kWh,flywheeel_max_discharge,flywheeel_max_charge,flywheel_cost_per_kWh,component_cost_max,local_power_cost,genset_capacity,li_capacity,flow_capacity,flywheel_capacity,load_min,pv_capacity
0,12,335,1,1,135,20,20,54,8,8,330,1141662,0.11,1003,982,1370,970,1225,614
1,12,335,1,1,135,20,20,54,8,8,330,789597,0.11,1150,776,1302,265,10,1050
2,12,335,1,1,135,20,20,54,8,8,330,1391675,0.11,1219,1300,1455,629,164,49
3,12,335,1,1,135,20,20,54,8,8,330,613807,0.11,1180,858,367,773,156,1029
4,12,335,1,1,135,20,20,54,8,8,330,525886,0.11,1118,1344,1387,222,1498,234

In [25]:
e_data = pd.read_csv('C:\\Users\\thesu\\Desktop\\Research 2022 Microgrid\\Research code repository\\Micro-Grid-ML-algo\\energy_storage_devices.csv')
display(e_data)

,type,max_charge,min_charge,max_cont_discharge_charge,max_peak_discharge,min_discharge,eff_charge,eff_discharge,self_discharge,capital_cost,marginal_cost,ramp_speed,resp_time,usable_start,usable_end,fixed_cap
0,li-ion,1.0,0.05,0.4,0.6,0.0,0.95,0.95,(-(233189*e^(-(493*('(-(10^12*ln(-e^-((100x-28...,650,NaN,NaN,NaN,NaN,NaN,NaN
1,flywheel,1.0,0.14,0.86*0.25,0.86*0.25,0.0,x**4/((1.01105*x**2+0.199918*x-0.165293)*(1.00...,x**4/((1.01105*x**2+0.199918*x-0.165293)*(1.00...,7.47775x+8.52548*x**(-1/2)+57.118,330,NaN,NaN,<1s,NaN,NaN,NaN
2,v2g,1.0,0.05,0.25,0.25,0.0,0.95,0.95,(-(233189*e^(-(493*('(-(10^12*ln(-e^-((100x-28...,"0, 1 unit per house",NaN,<1s,<1s (or aggregator?),NaN,NaN,48.0
3,flow,1.0,0.00,NaN,1.2*D5,0.0,0.883,0.883,0,1400,NaN,<1s,<1s,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN